repos:

  - repo: local
    hooks:
      - id: ktfmt
        name: ktfmt
        entry: ktfmt.sh
        language: script
        files: \.(kts|kt)$
        fail_fast: true
        verbose: true
        args: [ ]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: check-xml
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-illegal-windows-names
      - id: detect-private-key
      - id: no-commit-to-branch
